# This automation updates the repo.json when a gem.json file is changed

name: Update remote repository 

on:
  # Allows you to run this workflow manually from the Actions tag
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**gem.json'
        
run-name: Updating repo.json

jobs:
  Publish:
    name: Deploy
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      # Checkout this repository under $GITHUB_WORKSPACE/repo, so the job can access it
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: repo
          lfs: true
          fetch-depth: 0

      - name: Read gem.json
        id: gem-json 
        run: |
          {
            echo 'CONTENT<<EOF'
            cat ${{github.workspace}}/repo/gem.json
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Get gem info
        id: info
        env:
          GEM_NAME: ${{ fromJson( steps.gem-json.outputs.CONTENT ).gem_name }}
          GEM_VERSION: ${{ fromJson( steps.gem-json.outputs.CONTENT ).version }}
        run: |
          echo TEST
          echo $GEM_NAME
          echo $GEM_VERSION
          echo "version=$GEM_VERSION" >> "$GITHUB_OUTPUT"
          echo "name=$GEM_NAME" >> "$GITHUB_OUTPUT"

      # Checkout the o3de repository under $GITHUB_WORKSPACE/repo, so the job can access it
      # use sparse checkout to only get a few folders
      - name: Checkout o3de
        uses: actions/checkout@v4
        with:
          path: o3de
          repository: o3de/o3de
          ref: main
          lfs: false
          fetch-depth: 0
          sparse-checkout: |
            cmake
            python 
            scripts
            Templates
      
      - name: Install Python
        run: |
          o3de/python/get_python.sh

      - name: Create repo.json if needed
        run: |
          if ! test -f ${{github.workspace}}/repo/repo.json; then
            o3de/scripts/o3de.sh create-repo --repo-path ${{github.workspace}}/repo --repo-uri ${{github.server_url}}/${{github.repository}}.git --origin ${{github.repository_owner}}  --origin-url ${{github.server_url}}/${{github.repository}}
          fi

      - name: Update repo.json
        id: archive
        run: |
          o3de/scripts/o3de.sh edit-repo-properties --repo-path ${{github.workspace}}/repo --add-gem ${{github.workspace}}/repo --release-archive-path artifacts --download-prefix ${{github.server_url}}/${{github.repository}}/releases/download/${{steps.info.outputs.version}}

      - name: Commit repo.json Changes
        run: |
          git -C repo config --global user.name 'github-actions'
          git -C repo config --global user.email 'github-actions@users.noreply.github.com'
          git -C repo add gem.json repo.json
          git -C repo commit -am "Update gem.json repo.json"
          git -C tag ${{steps.info.outputs.version}}
          git -C repo push origin ${{steps.info.outputs.version}}
          
      # Creates a release tag based on inputs
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.11.1
        with:
          name: ${{ steps.vars.outputs.version }}
          tag: ${{ steps.vars.outputs.version }}
          body: |
            ## Release Notes
            ${{steps.vars.outputs.name}} ${{steps.vars.outputs.version}}
          draft: false
          prerelease: false
          artifacts: "artifacts/.*"
